export const SET_EXECERCISE_VISIBILITY = "SET_EXECERCISE_VISIBILITY";
export const ADD_EXERCISE = "ADD_EXERCISE";
export const ADD_EXERCISE_TO_SECTIONLIST = "ADD_EXERCISE_TO_SECTIONLIST";
export const DELETE_EXERCISE_FROM_SECTIONLIST = "DELETE_EXERCISE_FROM_SECTIONLIST";
export const CLEAR_CURRENT_WORKOUT = "CLEAR_CURRENT_WORKOUT";
export const UPDATE_EMPTY = "UPDATE_EMPTY";
export const ADD_DATE = "ADD_DATE";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const ADD_MARKED_DATE = "ADD_MARKED_DATE";
export const UPDATE_WEIGHT_DATA = "UPDATE_WEIGHT_DATA";
export const UPDATE_BFR_DATA = "UPDATE_BFR_DATA";
export const ADD_NEW_EXERCISE_LIST = "ADD_NEW_EXERCISE_LIST";
export const ADD_WEIGHT_TO_EXERCISE = "ADD_WEIGHT_TO_EXERCISE";
export const EDIT_WEIGHT_REPS_IN_EXERCISE = "EDIT_WEIGHT_REPS_IN_EXERCISE";
export const DELETE_EXERCISE_FROM_WORKOUTLIST =
    "DELETE_EXERCISE_FROM_WORKOUTLIST";

//Progress Page
export const ADD_PROGRESS_PHOTO = "ADD_PROGRESS_PHOTO";
export const SHOW_PROGRESS_MODAL = "SHOW_PROGRESS_MODAL";
export const SHOW_PROGRESS_PICKER = "SHOW_PROGRESS_PICKER";
export const CHANGE_TMP_URI = "CHANGE_TMP_URI";
export const UPDATE_WEIGHT_BFR_FROM_PROGRESS_PICS =
    "UPDATE_WEIGHT_BFR_FROM_PROGRESS_PICS";
export const DELETE_PICS_FROM_PROGRESS =
    "DELETE_PICS_FROM_PROGRESS";
export const DELETE_ONE_PIC_FROM_PROGRESS =
    "DELETE_ONE_PIC_FROM_PROGRESS";
export const CHANGE_CURRENT_DISPLAY_PIC =
    "CHANGE_CURRENT_DISPLAY_PIC";
export const SHOW_DELETE_CONFIRM_MODAL_IN_DISPLAY_PICTURE =
    "SHOW_DELETE_CONFIRM_MODAL_IN_DISPLAY_PICTURE";


//Custom workout
export const ADD_EXERCISE_SET_TO_CUSTOM_WORKOUT =
    "ADD_EXERCISE_SET_TO_CUSTOM_WORKOUT";
export const DELETE_EXERCISE_SET_FROM_CUSTOM_WORKOUT =
    "DELETE_EXERCISE_SET_FROM_CUSTOM_WORKOUT";
export const ADD_EXERCISE_SET_FROM_CUSTOM_WORKOUT_TO_CURRENT_WORKOUT =
    "ADD_EXERCISE_SET_FROM_CUSTOM_WORKOUT_TO_CURRENT_WORKOUT";


//Edit Library
export const SET_EDIT_LIBRARY_EXECERCISE_MODAL_VISIBILITY =
    "SET_EDIT_LIBRARY_EXECERCISE_MODAL_VISIBILITY";

