export const CHANGE_TAB = "CHANGE_TAB";
export const FETCH_CURRENT_WORKOUT = "FETCH_CURRENT_WORKOUT";
export const FETCH_CURRENT_WORKOUT_COMPLETE = "FETCH_CURRENT_WORKOUT_COMPLETE";
export const SET_EXECERCISE_VISIBILITY = "SET_EXECERCISE_VISIBILITY";
export const ADD_EXERCISE = "ADD_EXERCISE";
export const ADD_EXERCISE_TO_SECTIONLIST = "ADD_EXERCISE_TO_SECTIONLIST";
export const DELETE_EXERCISE_FROM_SECTIONLIST = "DELETE_EXERCISE_FROM_SECTIONLIST";
export const ADD_EXERCISE_COMPLETE = "ADD_EXERCISE_COMPLETE";
export const CLEAR_CURRENT_WORKOUT = "CLEAR_CURRENT_WORKOUT";
export const UPDATE_EMPTY = "UPDATE_EMPTY";
export const ADD_DATE = "ADD_DATE";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const ADD_MARKED_DATE = "ADD_MARKED_DATE";
export const UPDATE_WEIGHT_DATA = "UPDATE_WEIGHT_DATA";
export const UPDATE_BFR_DATA = "UPDATE_BFR_DATA";
export const ADD_NEW_EXERCISE_LIST = "ADD_NEW_EXERCISE_LIST";
export const GET_EXERCISE_LIST_FOR_PRESSED_DAY =
    "GET_EXERCISE_LIST_FOR_PRESSED_DAY";
export const ADD_PROGRESS_PHOTO = "ADD_PROGRESS_PHOTO";
export const SHOW_PROGRESS_MODAL = "SHOW_PROGRESS_MODAL";
export const SHOW_PROGRESS_PICKER = "SHOW_PROGRESS_PICKER";
export const CHANGE_TMP_URI = "CHANGE_TMP_URI";
export const ADD_WEIGHT_TO_EXERCISE = "ADD_WEIGHT_TO_EXERCISE";
export const EDIT_WEIGHT_REPS_IN_EXERCISE = "EDIT_WEIGHT_REPS_IN_EXERCISE";
export const DELETE_EXERCISE_FROM_WORKOUTLIST =
    "DELETE_EXERCISE_FROM_WORKOUTLIST";
export const UPDATE_WEIGHT_BFR_FROM_PROGRESS_PICS =
    "UPDATE_WEIGHT_BFR_FROM_PROGRESS_PICS";
export const DELETE_PICS_FROM_PROGRESS =
    "DELETE_PICS_FROM_PROGRESS";
export const DELETE_ONE_PIC_FROM_PROGRESS =
    "DELETE_ONE_PIC_FROM_PROGRESS";

